### List vs Tuple

In [2]:
L = [1, 2, 3, 4, 5]
L[0] = 10
print(L)

[10, 2, 3, 4, 5]


In [3]:
T = (1, 2, 3, 4, 5)
T[0] = 10

TypeError: 'tuple' object does not support item assignment

- 리스트는 가변, 튜플은 불변
- 따라서 리스트는 사전의 key로 사용할 수 없지만 튜플은 가능

In [5]:
# 순회 속도
large_L = list(range(100000))
large_T = tuple(range(100000))

import time
start_time = time.time()
for val1 in large_L:
    pass
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
for val2 in large_T:
    pass
end_time = time.time()
print(end_time - start_time)  

0.0030333995819091797
0.0019676685333251953


튜플이 약간 더 빨라서 변경할 필요가 없을 경우 튜플이 유용

In [7]:
# 합치기
L1 = [1, 2, 3]
L2 = [4, 5, 6]
print(L1 + L2)

[1, 2, 3, 4, 5, 6]


In [6]:
# 소괄호없이 튜플 만들기
T = 1, 2, 3, 4
print(T)

(1, 2, 3, 4)


In [8]:
# 위치 찾기 함수: index
L5 = [1, 3, 2, 1, 4]
print("1의 위치:{}".format(L5.index(1)))
print("3의 위치:{}".format(L5.index(3)))

1의 위치:0
3의 위치:1


In [9]:
# 요소 추가 함수: insert
L2 = [4, 5, 1, 2, 10]
L2.insert(1, 7)
print(L2)
# 요소 제거 함수: remove
L3 = [1, 3, 2, 1, 4]
L3.remove(1)
print(L3)
# 요소가 여러 개면 맨 앞의 하나만 지워짐.

[4, 7, 5, 1, 2, 10]
[3, 2, 1, 4]


In [10]:
# 튜플을 이용한 여러 값 동시에 입력받기 및 Swap
a, b = 1, 2 # a = 1; b = 2
print(a, b)
b, a = a, b # Swap
print(a, b)

1 2
2 1


In [ ]:
# 함수의 가변 인자로 사용
def f(*x): # *: 인자수가 정해지지 않았음을 의미
    print("입력된 데이터의 타입:{}".format(type(x)))
    sum_x = 0
    product_x = 1
    for val in x:
        sum_x += val
        product_x *= val
    return sum_x, product_x
        
S, P = f(1, 2, 3, 4, 5) # 출력을 각각 S와 P로 받음
print(S, P)

itertools

In [12]:
import itertools
for a, b, c in itertools.product(range(3), range(3), range(3)):
    print(a, b, c)

0 0 0
0 0 1
0 0 2
0 1 0
0 1 1
0 1 2
0 2 0
0 2 1
0 2 2
1 0 0
1 0 1
1 0 2
1 1 0
1 1 1
1 1 2
1 2 0
1 2 1
1 2 2
2 0 0
2 0 1
2 0 2
2 1 0
2 1 1
2 1 2
2 2 0
2 2 1
2 2 2


In [13]:
for a, b, c in zip(range(5), range(5), range(5)):
    print(a, b, c)

0 0 0
1 1 1
2 2 2
3 3 3
4 4 4


In [14]:
# itertools.combination 예제
# L에서 2개로 이뤄진 가능한 모든 조합 뽑기
L = ['a', 'b', 'c', 'd']
for comb in itertools.combinations(L, 2):
    print(comb)

('a', 'b')
('a', 'c')
('a', 'd')
('b', 'c')
('b', 'd')
('c', 'd')


In [15]:
# L에서 가능한 모든 조합 뽑기
for r in range(1, len(L) + 1):
    for comb in itertools.combinations(L, r):
        print(comb)

('a',)
('b',)
('c',)
('d',)
('a', 'b')
('a', 'c')
('a', 'd')
('b', 'c')
('b', 'd')
('c', 'd')
('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'd')
('b', 'c', 'd')
('a', 'b', 'c', 'd')


List comprehension

In [16]:
X = [1, 2, 3, 'a', 'b']
Y = [3, 1, 2, 'c', 4]

L4 = [x + y for x, y in itertools.product(X, Y) if type(x) == type(y) == int]
L4

[4, 2, 3, 5, 5, 3, 4, 6, 6, 4, 5, 7]

dictionary comprehension

In [17]:
dic1 = {x:y for x, y in zip(range(10), range(10))}
dic1

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [18]:
dic = {1:'NaN', 2:2, 3:4, 4:'NaN'}
dic2 = {x:y for x, y in dic.items() if y != 'NaN'}
dic2

{2: 2, 3: 4}

## numpy

In [21]:
import numpy as np

a = np.zeros(10, dtype = int) # 0으로 채운 배열 생성
b = np.ones((3, 5), dtype = float) #1로 채운 배열 생성
c = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기 
d = np.arange(0, 20, 2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성
e = np.linspace(0, 1, 5) # 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
f = np.random.random((3,3)) # 3*3 크기의 난수 배열 생성
g = np.random.normal(0, 1, (3, 3)) # 평균 0, 표준 편차 1의 정규 분포를 따르는 3*3 난수 배열
h = np.random.randint(0, 10, (3, 3)) # [0, 10) 구간의 임의로 정수로 채운 3*3 배열 만들기
i = np.eye(3) # 크기 3의 단위 행렬 만들기

print("np.zeros(10, dtype = int):\n", a)
print("\nnp.ones((3, 5), dtype = float):\n", b)
print("\nnp.full((3,5), 3.14):\n", c)
print("\nnp.arange(0, 20, 2):\n", d)
print("\nnp.linspace(0, 1, 5):\n", e)
print("\nnp.random.random((3,3)):\n", f)
print("\nnp.random.normal(0, 1, (3, 3)):\n", g)
print("\nnp.random.randint(0, 10, (3, 3)):\n", h)
print("\nnp.eye(3):\n", i)

np.zeros(10, dtype = int):
 [0 0 0 0 0 0 0 0 0 0]

np.ones((3, 5), dtype = float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

np.full((3,5), 3.14):
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

np.arange(0, 20, 2):
 [ 0  2  4  6  8 10 12 14 16 18]

np.linspace(0, 1, 5):
 [0.   0.25 0.5  0.75 1.  ]

np.random.random((3,3)):
 [[0.49173074 0.46304299 0.00268079]
 [0.68930292 0.65971862 0.4622951 ]
 [0.72336011 0.70926002 0.71550376]]

np.random.normal(0, 1, (3, 3)):
 [[-0.02640436  0.25869072  0.79028337]
 [ 0.97139198  0.57392848 -2.28348274]
 [ 1.02665627  0.86635498 -1.12329301]]

np.random.randint(0, 10, (3, 3)):
 [[6 6 3]
 [0 7 0]
 [5 1 5]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# 2차원 배열의 인덱싱 및 슬라이싱
x2 = np.random.random(size = (10, 5))
print("x2[0:3, 2:4]\n", x2[0:3, 2:4])

x2[0:3, 2:4]
 [[0.16778874 0.02305253]
 [0.32663603 0.25817092]
 [0.75650858 0.80628496]]


유니버설 함수

- ndarray의 개별 요소에 반복 연산을 빠르게 수행
- 단순 반복문에 비해 매우 빠름

In [23]:
# 루프와 유니버설 함수의 속도 비교
arr_1 = np.random.randint(1, 10, size = 10 ** 8)
arr_2 = np.random.randint(1, 10, size = 10 ** 8)
import time
### 리스트를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = []
for val1, val2 in zip(arr_1, arr_2):
    output.append(val1 + val2)
t2 = time.time()
print("반복문을 사용한 경우:", round(t2 - t1, 4))

### 유니버설 함수를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = arr_1 + arr_2
t2 = time.time()
print("유니버설 함수를 사용한 경우:", round(t2 - t1, 4))

반복문을 사용한 경우: 38.4306
유니버설 함수를 사용한 경우: 11.3172


In [24]:
# 브로드캐스팅 예시: z - normalization
X = np.random.random((10, 3))
Xmean = X.mean(axis = 0) # 열별 평균 크기: (1, 3)
Xstd = X.std(axis = 0) # 열별 표준편차 크기: (1, 3)

Z = (X - Xmean) / Xstd

print("X:", X)
print("\nXmean:\n", Xmean)
print("\nXstd:\n", Xstd)
print("\nZ:\n", Z)

X: [[0.22543134 0.99860555 0.98367984]
 [0.18185618 0.52383075 0.78330733]
 [0.72287432 0.17779657 0.44295914]
 [0.93029692 0.40142867 0.99880821]
 [0.36596234 0.89774133 0.69509612]
 [0.18277619 0.49873253 0.69750447]
 [0.68219194 0.60065098 0.90376948]
 [0.25609112 0.03330874 0.19355128]
 [0.83753592 0.60829148 0.54093718]
 [0.79749719 0.81298674 0.63901808]]

Xmean:
 [0.51825135 0.55533733 0.68786311]

Xstd:
 [0.28667373 0.28773311 0.23840303]

Z:
 [[-1.02143997  1.54055338  1.24082623]
 [-1.17344259 -0.10949933  0.40034816]
 [ 0.71378348 -1.3121214  -1.02726873]
 [ 1.43733286 -0.53490077  1.30428335]
 [-0.53122763  1.19000555  0.0303394 ]
 [-1.17023332 -0.19672678  0.04044143]
 [ 0.57187171  0.157485    0.90563602]
 [-0.91448988 -1.81428058 -2.07342934]
 [ 1.11375595  0.18403911 -0.61629223]
 [ 0.97408939  0.89544581 -0.2048843 ]]


In [25]:
L = np.array([1, 2, 3, 4, 5])
cond = L >= 3
print(sum(cond))
print(L[cond])

3
[3 4 5]


## Pandas

In [26]:
import pandas as pd
# S = pd.Series({"a": 1, "b": 2, "c":3, "d":4})
# dict

S = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
S

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# 모든 행과 모든 열을 보여주기
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# None에 숫자 들어가면 그 개수만큼